name: easy_pizza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  customizable_counter: ^1.0.4
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  provider: ^6.1.2
  uuid : ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
  - images/pizza.png