name: easy_pizza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  customizable_counter: ^1.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^14.1.4
  json_annotation: ^4.9.0
  provider: ^6.1.2
  uuid : ^4.4.0
  web_socket_channel: ^3.0.0
  badges: ^3.1.2
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons : ^0.13.1
  
flutter_native_splash:
  color: white
  image: images/easypizzas.png

flutter:
  uses-material-design: true

  assets:
  - images/pizza.png
  - images/easypizzas-logo.png
  - easy_pizza.env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/easypizzas-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"